/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_qupai_myapplication_DecoderTest */

#ifndef _Included_welsenctest_WelsEncTest_encoderTest
#define _Included_welsenctest_WelsEncTest_encoderTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_encoder_test_alivc_aliyun_com_encodertest_EncoderTest
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_welsenc_WelsEncTest_encoderTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
